# Generated by Django 5.0.2 on 2024-03-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyField',
            fields=[
                ('survey_field_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ra', models.DecimalField(decimal_places=6, max_digits=10)),
                ('dec', models.DecimalField(decimal_places=6, max_digits=10)),
                ('l', models.DecimalField(decimal_places=6, max_digits=10)),
                ('b', models.DecimalField(decimal_places=6, max_digits=10)),
                ('program', models.CharField(max_length=255)),
                ('exposure_time', models.DecimalField(decimal_places=6, max_digits=10)),
                ('cadence', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ephemeris', models.DecimalField(decimal_places=6, max_digits=10)),
                ('period', models.DecimalField(decimal_places=6, max_digits=10)),
                ('observations', models.IntegerField()),
                ('moon_phase', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'survey_field',
            },
        ),
        migrations.CreateModel(
            name='ObsQueue',
            fields=[
                ('queue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.surveyfield')),
            ],
            options={
                'db_table': 'obs_queue',
            },
        ),
    ]
