# Generated by Django 5.0.2 on 2024-03-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bns', models.FloatField()),
                ('nsbh', models.FloatField()),
                ('bbh', models.FloatField()),
                ('terrestrial', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ns', models.FloatField()),
                ('has_remnant', models.FloatField()),
                ('has_mass_gap', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EventSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCoincObservatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observatory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCoincSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GWAlertUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwalert_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superevent_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('far', models.FloatField()),
                ('significant', models.BooleanField()),
                ('duration', models.FloatField()),
                ('central_frequency', models.FloatField()),
                ('skymap', models.URLField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.eventclassification')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.eventgroup')),
                ('instruments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.eventinstrument')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.eventpipeline')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.eventproperties')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.eventsearch')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCoinc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcn_notice_id', models.BigIntegerField()),
                ('ivorn', models.URLField()),
                ('time_difference', models.FloatField()),
                ('combined_skymap', models.URLField()),
                ('observatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.externalcoincobservatory')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.externalcoincsearch')),
            ],
        ),
        migrations.CreateModel(
            name='GWAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField()),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alerttype')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.event')),
                ('external_coinc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.externalcoinc')),
                ('urls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.gwalerturl')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.notice')),
                ('superevent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.superevent')),
            ],
        ),
    ]
